### ISSUE TITLE
Runtime error in updated Brevitas

### ISSUE THREAD

**Issue by YouanLi** [Xilinx/brevitas#217]
Hello there,

I want to ask which modules have been changed in the updated Brevitas compared to the previous ones.
My code can run in the previous brevitas, but when I switch to the newer one, the following problems occur.

Training done in 153.091 s
Evaluating best model on testset...
Traceback (most recent call last):
  File "main.py", line 372, in <module>
    main()
  File "main.py", line 252, in main
    test_acc = validate(test_net, testloader, device, criterion)
  File "main.py", line 312, in validate
    output = net(images)
  File "/home/../miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/rwthfs/rz/cluster/home/../../models/densenet.py", line 207, in forward
    out = self.conv1(x)
  File "/home/../miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/../miniconda3/lib/python3.8/site-packages/brevitas/nn/quant_conv.py", line 231, in forward
    return self.forward_impl(input)
  File "/home/../miniconda3/lib/python3.8/site-packages/brevitas/nn/quant_layer.py", line 313, in forward_impl
    quant_weight = self.quant_weight()
  File "/home/../miniconda3/lib/python3.8/site-packages/brevitas/nn/mixin/parameter.py", line 122, in quant_weight
    return self.weight_quant(self.weight)
  File "/home/../miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/../miniconda3/lib/python3.8/site-packages/brevitas/proxy/parameter_quant.py", line 130, in forward
    out, scale, bit_width = self.tensor_quant(x)
  File "/home/../miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/../miniconda3/lib/python3.8/site-packages/brevitas/core/quant.py", line 672, in forward
    y = self.int_quant(scale, int_scale, msb_clamp_bit_width, x)
  File "/home/../miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/../miniconda3/lib/python3.8/site-packages/brevitas/core/quant.py", line 440, in forward
    y_int = self.to_int(scale, int_scale, msb_clamp_bit_width, x)
  File "/home/../miniconda3/lib/python3.8/site-packages/brevitas/core/quant.py", line 418, in to_int
    y = self.tensor_clamp_impl(y, min_val=min_int_val, max_val=max_int_val)
  File "/home/../miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/../miniconda3/lib/python3.8/site-packages/brevitas/core/function_wrapper.py", line 126, in forward
    return tensor_clamp_ste(x, min_val, max_val)
  File "/home/../miniconda3/lib/python3.8/site-packages/brevitas/function/ops_ste.py", line 152, in tensor_clamp_ste
    output = tensor_clamp_ste_fn.apply(x, min_val, max_val)
  File "/home/../miniconda3/lib/python3.8/site-packages/brevitas/function/autograd_ops.py", line 109, in forward
    y = torch.where(x > max_val, max_val, x)
RuntimeError: Expected condition, x and y to be on the same device, but condition is on cuda:0 and x and y are on cpu and cuda:0 respectively

**Comment by volcacius** [comment]
Hello,

Can you please point me to the commit of Brevitas that is working for you?

Thanks

Alessandro

**Comment by YouanLi** [comment]
hi Alessandro,

Thanks for your answering. I use  load_state_dict(), I guess that probably causes the problem.

And the version which I use is  [this](https://github.com/Xilinx/brevitas/commit/2c0019fa29f37b73c793ebe4221d90392332ec36)

Thanks a lot,
