### ISSUE TITLE
Is this a bug? Ask for help and discussion.

### ISSUE THREAD

**Issue by YZW-explorer** [Xilinx/brevitas#274]
**The error is as follows：**
Traceback (most recent call last):
File "D:\anaconda3\envs\DeepLearnning\lib\site-packages\brevitas\core\function_wrapper\shape.py", line 75, in forward
    return x.view(shape)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
**code:**
@brevitas.jit.script_method
    def forward(self, x: torch.Tensor):
        shape = self.shape(x)
        return x.view(shape)

**This is the core code. When I make the following changes, the error is resolved.**

**Manually modified code：**
    @brevitas.jit.script_method
    def forward(self, x: torch.Tensor):
        shape = self.shape(x)
        return x.contiguous().view(shape)

**Comment by volcacius** [comment]
Thanks for reporting this. What layer is this with?

**Comment by YZW-explorer** [comment]
This is the detailed error message： 
File "D:\anaconda3\envs\DeepLearnning\lib\site-packages\brevitas\proxy\runtime_quant.py", line 163, in forward
    y = self.fused_activation_quant_proxy(y)
  File "D:\anaconda3\envs\DeepLearnning\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\DeepLearnning\lib\site-packages\brevitas\proxy\runtime_quant.py", line 103, in forward
    x, output_scale, output_zp, output_bit_width = self.tensor_quant(x)
  File "D:\anaconda3\envs\DeepLearnning\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\DeepLearnning\lib\site-packages\brevitas\core\quant\int.py", line 194, in forward
    threshold = self.scaling_impl(x)
  File "D:\anaconda3\envs\DeepLearnning\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\DeepLearnning\lib\site-packages\brevitas\core\scaling\standalone.py", line 279, in forward
    stats_input = self.stats_input_view_shape_impl(stats_input)
  File "D:\anaconda3\envs\DeepLearnning\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\DeepLearnning\lib\site-packages\brevitas\core\function_wrapper\shape.py", line 75, in forward
    return x.view(shape)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by volcacius** [comment]
Thanks, i'll switch to reshape.
