### ISSUE TITLE
The error when 'export_finn_onnx' for 'quant_vgg19_bn()'

### ISSUE THREAD

**Issue by simplelins** [Xilinx/brevitas#294]
The error as below:
`test_vgg19_bn
Traceback (most recent call last):
  File "test_resnet50_finn_export.py", line 188, in <module>
    test_vgg19_bn()
  File "test_resnet50_finn_export.py", line 165, in test_vgg19_bn
    export_finn_onnx(vgg19, (1, 3, 224, 224), finn_onnx)
  File "/home/lww/project/12_FPGA/brevitas/src/brevitas/export/__init__.py", line 12, in export_finn_onnx
    return FINNManager.export_onnx(*args, **kwargs)
  File "/home/lww/project/12_FPGA/brevitas/src/brevitas/export/onnx/base.py", line 97, in export_onnx
    module.apply(lambda m: _set_export_mode(m, enabled=True))
  File "/home/lww/usr/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 445, in apply
    module.apply(fn)
  File "/home/lww/usr/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 445, in apply
    module.apply(fn)
  File "/home/lww/usr/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 446, in apply
    fn(self)
  File "/home/lww/project/12_FPGA/brevitas/src/brevitas/export/onnx/base.py", line 97, in <lambda>
    module.apply(lambda m: _set_export_mode(m, enabled=True))
  File "/home/lww/project/12_FPGA/brevitas/src/brevitas/export/base.py", line 99, in _set_export_mode
    m.export_mode = enabled
  File "/home/lww/usr/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 826, in __setattr__
    object.__setattr__(self, name, value)
  File "/home/lww/project/12_FPGA/brevitas/src/brevitas/nn/mixin/base.py", line 166, in export_mode
    self.export_handler.prepare_for_export(self)
  File "/home/lww/project/12_FPGA/brevitas/src/brevitas/export/onnx/finn/handler/parameter.py", line 101, in prepare_for_export
    quant_output_bit_width_tensor)
  File "/home/lww/project/12_FPGA/brevitas/src/brevitas/export/onnx/finn/handler/parameter.py", line 59, in maybe_quant_bias
    bias /= quant_weight_scale
RuntimeError: output with shape [4096] doesn't match the broadcast shape [1, 4096]`

(Pdb) p bias.shape
torch.Size([4096])
(Pdb) p quant_weight_scale.shape
torch.Size([1, 4096])

And I add this line, please check!
![image](https://user-images.githubusercontent.com/53635925/115141372-7550ac00-a06e-11eb-9736-b6b6bbe30c7d.png)

**Comment by volcacius** [comment]
Thanks, this is fixed in master now.
