### ISSUE TITLE
Dataflow FPGA acceleration with FINN Error

### ISSUE THREAD

**Issue by YZW-explorer** [Xilinx/brevitas#317]
Hello author! it's me again!
I am trying to use Dataflow FPGA acceleration with FINN but there is a problem.
my code:
from brevitas.export import FINNManager
FINNManager.export(model, input_shape=(1, 3, 32, 32), export_path='model.onnx')

Traceback (most recent call last):
  File "transfertoonnx.py", line 85, in <module>
    main(args)
  File "transfertoonnx.py", line 78, in main
    bo.export_finn_onnx(model,input_shape,export_onnx_path)
  File "python3.8/site-packages/brevitas/export/__init__.py", line 13, in export_finn_onnx
    return FINNManager.export(*args, **kwargs)
  File "python3.8/site-packages/brevitas/export/onnx/finn/manager.py", line 112, in export
    onnx_model = cls.export_onnx(module, input_shape, export_path, input_t, **kwargs)
  File "python3.8/site-packages/brevitas/export/onnx/base.py", line 76, in export_onnx
    raise ModuleNotFoundError("Installation of ONNX is required.")
ModuleNotFoundError: Installation of ONNX is required.

**Comment by YZW-explorer** [comment]
But I have used pip install to download the onnx package

**Comment by volcacius** [comment]
Try downgrading to onnx 1.8.1 .

**Comment by YZW-explorer** [comment]
Thank you so much !!!
