### ISSUE TITLE
Error in ONNX standard export: is there any particular requirement on layer quantization instance?

### ISSUE THREAD

**Issue by rachhele** [Xilinx/brevitas#329]
Hello,
I'm having trouble in exporting my model to ONNX standard. I notice that to export a QuantConv2d layer to ONNX seems mandatory to set also a quantization for the input and the output tensor, is that true? I would like to quantize only the weights of my layers.

As example, this script reports the following errors:
```python
import torch
import torch.nn as nn 
import brevitas.nn as qnn
from brevitas.quant import Int8WeightPerTensorFloat 
from brevitas.export import StdONNXManager

class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()
        self.conv1 = qnn.QuantConv2d(3, 6, 5, weight_bit_width=3)

    def forward(self, x):
        out = self.conv1(x)
        return out

onnx_testnet = TestNet()

StdONNXManager.export(onnx_testnet, input_shape=(1, 3, 256, 256), export_path='onnx_testnet.onnx')
```

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    StdONNXManager.export(onnx_lenet, input_shape=(1, 3, 256,256), export_path='onnx_lenet.onnx')
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\base.py", line 57, in export
    return cls.export_onnx(module, input_shape, export_path, input_t, **kwargs)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\standard\manager.py", line 97, in export_onnx
    output = super().export_onnx(module, input_shape, export_path, input_t, opset_version=OPSET, **kwargs)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\base.py", line 98, in export_onnx
    module.apply(lambda m: cls.set_export_mode(m, enabled=True))
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 440, in apply
    module.apply(fn)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 441, in apply
    fn(self)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\base.py", line 98, in <lambda>
    module.apply(lambda m: cls.set_export_mode(m, enabled=True))
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\standard\manager.py", line 83, in set_export_mode
    _set_layer_export_mode(module, enabled)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\base.py", line 100, in _set_layer_export_mode
    m.export_mode = enabled
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 819, in __setattr__
    object.__setattr__(self, name, value)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\nn\mixin\base.py", line 166, in export_mode
    self.export_handler.prepare_for_export(self)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\standard\handler\parameter.py", line 140, in prepare_for_export
    self.validate(module)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\standard\handler\parameter.py", line 36, in validate
    assert module.is_output_quant_enabled
AssertionError
```
Furthermore, I notice that in the following file there is a check on the quantization of the weights and the output, why there is also a check on the bit_width of the input quantization? https://github.com/Xilinx/brevitas/blob/02693c41f6ea135f11ae7d415afd947358aee6ae/src/brevitas/export/onnx/standard/handler/parameter.py#L34-L43

Actually, running this script
```python
import torch
import torch.nn as nn 
import brevitas.nn as qnn
from brevitas.quant import Int8WeightPerTensorFloat 
from brevitas.export import StdONNXManager
from brevitas.quant import ShiftedUint8ActPerTensorFloat as ActQuant

class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()
        self.conv1 = qnn.QuantConv2d(3, 6, 5, weight_bit_width=8, bias=False, output_quant=ActQuant, output_bit_width=8)

    def forward(self, x):
        out = self.conv1(x)
        return out

onnx_testnet = TestNet()

StdONNXManager.export(onnx_testnet, input_shape=(1, 3, 256, 256), export_path='onnx_testnet.onnx')
```
I got this error:
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    StdONNXManager.export(onnx_testnet, input_shape=(1, 3, 256, 256), export_path='onnx_testnet.onnx')
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\base.py", line 57, in export
    return cls.export_onnx(module, input_shape, export_path, input_t, **kwargs)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\standard\manager.py", line 97, in export_onnx
    output = super().export_onnx(module, input_shape, export_path, input_t, opset_version=OPSET, **kwargs)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\base.py", line 98, in export_onnx
    module.apply(lambda m: cls.set_export_mode(m, enabled=True))
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 440, in apply
    module.apply(fn)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 441, in apply
    fn(self)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\base.py", line 98, in <lambda>
    module.apply(lambda m: cls.set_export_mode(m, enabled=True))
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\standard\manager.py", line 83, in set_export_mode
    _set_layer_export_mode(module, enabled)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\base.py", line 100, in _set_layer_export_mode
    m.export_mode = enabled
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 819, in __setattr__
    object.__setattr__(self, name, value)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\nn\mixin\base.py", line 166, in export_mode
    self.export_handler.prepare_for_export(self)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\standard\handler\parameter.py", line 140, in prepare_for_export
    self.validate(module)
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\onnx\standard\handler\parameter.py", line 38, in validate
    cls.validate_8b_bit_width(module.quant_input_bit_width())
  File "C:\Users\rache\AppData\Local\Programs\Python\Python38\lib\site-packages\brevitas\export\common\handler.py", line 12, in validate_8b_bit_width
    raise RuntimeError("Bit width cannot be None")
RuntimeError: Bit width cannot be None
```

Could you give me some hints on this kind of export? Thanks a lot :slightly_smiling_face:

**Comment by rgb000000** [comment]
You can see [qlinearconv](https://github.com/onnx/onnx/blob/master/docs/Operators.md#qlinearconv).
> The convolution operator consumes a quantized input tensor, its scale and zero point, a quantized filter, its scale and zero point, and output's scale and zero point, and computes the quantized output. Each scale and zero-point pair must have same shape. It means they must be either scalars (per tensor) or 1-D tensors (per output channel). Each input or output and its related zero point must have same type. When bias is present it must be quantized using scale = input scale * weight scale and zero point as 0.

On the other hand, onnx maybe only support int8 input now.

**Comment by volcacius** [comment]
Hey Rachele,
As @rgb000000 quantized layers in standard ONNX require a certain structure. To fullfill the requirement in Brevitas, you need two things:
- have output_quant set to an 8b quantizer in QuantLinear/QuantConv1d/2d
- Have an 8b quantized input that is passed to QuantLinear/QuantConv1d/2d. There are two ways to achieve that. Either you set input_quant, or you make sure that an 8b QuantTensor is passed from the previous layer. 

It wouldn't make much sense to set input_quant in every layer since you are already setting output_quant in every layer, you would have that almost every activation is quantized twice. What makes sense then is to set input_quant only on the first layer, and then set return_quant_tensor=True in every layer (except on the last one if you don't wanna have a QuantTensor as output of the network). This way you propagate the output_quant of a layer to the next one. Extending your example:
```python

import torch
import torch.nn as nn 
import brevitas.nn as qnn
from brevitas.quant import Int8WeightPerTensorFloat 
from brevitas.export import StdONNXManager
from brevitas.quant import ShiftedUint8ActPerTensorFloat as ActQuant

class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()
        self.conv1 = qnn.QuantConv2d(3, 6, 5, weight_bit_width=8, bias=False, input_quant=ActQuant, output_quant=ActQuant, return_quant_tensor=True)
        self.conv2 = qnn.QuantConv2d(6, 6, 5, weight_bit_width=8, bias=False, output_quant=ActQuant)
    def forward(self, x):
        out = self.conv1(x)
        out = self.conv2(x)
        return out

onnx_testnet = TestNet()

StdONNXManager.export(onnx_testnet, input_shape=(1, 3, 256, 256), export_path='onnx_testnet.onnx')
```

**Comment by rachhele** [comment]
Thanks a lot! :smile: I finally manage to export my model to ONNX! 

By the way I'm having trouble in running the ONNX file, the error is the following:
```NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node QLinearConv_25:QLinearConv(10)```
Do you have any idea?

**Comment by volcacius** [comment]
I would make sure you are running a recent version of ONNXRuntime. When it comes to quantized nodes, there are some combinations of things that are supported in the ONNX standard but not ONNXRuntime, at least on older versions.

**Comment by Giuseppe5** [comment]
Closing this, feel free to reopen if you have more questions!
