### ISSUE TITLE
`QuantHardTanh` with signed outputs

### ISSUE THREAD

**Issue by SpontaneousDuck** [Xilinx/brevitas#348]
I am trying to implement a `QuantHardTanh` layer in my code and set the outputs to be signed. My code is below:
```
class MyActQuant(Int8ActPerTensorFloatMinMaxInit, ActQuantSolver):
    scaling_impl_type = ScalingImplType.STATS
    scaling_stats_op = StatsOp.MIN_MAX
    signed = True
    narrow_range = True

layers.append(qnn.QuantHardTanh(bit_width=4, act_quant=MyActQuant))
```

When running with this code, I get the below error. Setting `signed = False` does not show the error so I am assuming something is not getting set? I would like to use `ScalingImplType.STATS` or `ScalingImplType.PARAMETER_FROM_STATS` as that is what the rest of my activation layers use. 

```
Traceback (most recent call last):
  File "test.py", line 75, in <module>
    model = my_model(n_classes=len(class_labels), **model_params)
  File "/home/jovyan/workspace/Models.py", line 369, in __init__
    layers.append(qnn.QuantHardTanh(bit_width=4, act_quant=MyActQuant))
  File "/opt/conda/lib/python3.8/site-packages/brevitas/nn/quant_activation.py", line 112, in __init__
    QuantNLAL.__init__(
  File "/opt/conda/lib/python3.8/site-packages/brevitas/nn/quant_layer.py", line 74, in __init__
    QuantNonLinearActMixin.__init__(
  File "/opt/conda/lib/python3.8/site-packages/brevitas/nn/mixin/act.py", line 149, in __init__
    QuantProxyMixin.__init__(
  File "/opt/conda/lib/python3.8/site-packages/brevitas/nn/mixin/base.py", line 100, in __init__
    quant = quant_injector.proxy_class(self, quant_injector)
  File "/opt/conda/lib/python3.8/site-packages/brevitas/proxy/runtime_quant.py", line 110, in __init__
    super(ActQuantProxyFromInjector, self).__init__(quant_layer, quant_injector)
  File "/opt/conda/lib/python3.8/site-packages/brevitas/proxy/quant_proxy.py", line 65, in __init__
    self.add_tracked_module(quant_layer)
  File "/opt/conda/lib/python3.8/site-packages/brevitas/proxy/quant_proxy.py", line 104, in add_tracked_module
    self.init_tensor_quant()
  File "/opt/conda/lib/python3.8/site-packages/brevitas/proxy/runtime_quant.py", line 123, in init_tensor_quant
    act_impl = self.quant_injector.act_impl
  File "/opt/conda/lib/python3.8/site-packages/brevitas/inject/__init__.py", line 128, in __getattr__
    dependency = attribute(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 234, in __init__
    assert self.max_val > self.min_val
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```

Environment:
Pytorch: 1.9.0
Brevitas: 0.6.0

Thanks for the help!!

**Comment by volcacius** [comment]
Hello,

My understanding is that you don't need a QuantHardTanh, you need a QuantIdentity. There are two differences between QuantHardTanh and QuantIdentity:
- With quantization disabled (act_quant=None), QuantIdentity behaves like an Identity, QuantHardTanh behaves like a HardTanh.
- With quantization enabled, by default QuantHardTanh is initialized with user-defined min_val and max_val, while QuantIdentity is initialized based on statistics. After that they behave they same.

The code you wrote should work in principle, basically you are saying that you want your QuantHardTanh to behave like a QuantIdentity, but I see there is a minor issue that prevents the initialization from going through correctly. I wouldn't even bother though, you can simply do the following to get the result you want:

```
class MyActQuant(Int8ActPerTensorFloat, ActQuantSolver):
    scaling_impl_type = ScalingImplType.STATS
    scaling_stats_op = StatsOp.MIN_MAX
    narrow_range = True
    # you don't signed=True, it's already in Int8ActPerTensorFloat

qnn.QuantIdentity(bit_width=4, act_quant=MyActQuant) 
qnn.QuantIdentity(bit_width=4, act_quant=MyActQuant)
```

Note that you probably want to use StatsOp.MAX and not StatsOp.MIN_MAX. The naming is a bit confusing, but if you do the math basically StatsOp.MIN_MAX makes sense when you do unsigned quantization with a zero-point like MinUintZeroPoint, which is not your case.

**Comment by SpontaneousDuck** [comment]
Makes sense! Thanks for that explanation.
