### ISSUE TITLE
creating two instances from the same class

### ISSUE THREAD

**Issue by MaenMallah** [Xilinx/brevitas#350]
Hello, 

I have a use-case where I need to create two objects from the same class and pass them to one quantizer. In the standard dependencies tool that you use, I can do this using nested classes and this. Here is an example:

```Python
from brevitas.inject import ExtendedInjector, this
from dependencies import Injector
class Complex():
    def __init__(self, re, im):
        self.re = re
        self.im = im
    def __str__(self):
        return str((self.re, self.im))
class ADD_Complex():
    def  __init__(self, x, y):
        self.x = x 
        self.y = y
    def calc(self):
        z = Complex(self.x.re  + self.y.re, self.x.im + self.y.im)
        print(z.re, z.im)
        return z

class Container(Injector):
    adder = ADD_Complex
    x = this.X.complex
    y = this.Y.complex
    class X(Injector):
        complex = Complex
        re = 5
        im = 10
    class Y(Injector):
        complex = Complex
        re = -1
        im = 0

print(Container.adder.calc())
```

This works fine and I can create different x,y Complex objects and use them inside ADD_Complex. However, when I change that to the ExtendedInjector by brevitas I get the following error:

Traceback (most recent call last):
  File "/home/mhm/workspace/andante-vad/andante_vad/custom_brevitas/examples/Untitled-1.py", line 33, in <module>
    print(Container.adder.calc())
  File "/home/mhm/workspace/andante-vad/andante_vad/ANDANTE/lib/python3.8/site-packages/brevitas/inject/__init__.py", line 128, in __getattr__
    dependency = attribute(**kwargs)
  File "/home/mhm/workspace/andante-vad/andante_vad/ANDANTE/lib/python3.8/site-packages/_dependencies/this.py", line 51, in __call__
    result = getattr(result, symbol)
  File "/home/mhm/workspace/andante-vad/andante_vad/ANDANTE/lib/python3.8/site-packages/brevitas/inject/__init__.py", line 130, in __getattr__
    spec = _make_init_spec(dependency)
  File "/home/mhm/workspace/andante-vad/andante_vad/ANDANTE/lib/python3.8/site-packages/_dependencies/classes.py", line 13, in _make_init_spec
    args, have_defaults = _make_func_spec(dependency.__init__, name, owner_message)
  File "/home/mhm/workspace/andante-vad/andante_vad/ANDANTE/lib/python3.8/site-packages/_dependencies/func.py", line 27, in _make_func_spec
    _check_varargs(funcname, varargs, kwargs)
  File "/home/mhm/workspace/andante-vad/andante_vad/ANDANTE/lib/python3.8/site-packages/_dependencies/checks/func.py", line 26, in _check_varargs
    raise DependencyError(message.format(name))
_dependencies.exceptions.DependencyError: X.__init__ have arbitrary argument list and keyword arguments

Is there a different way to do this functionality within the ExtendedInjector? 

Regards,
Maen

**Comment by volcacius** [comment]
Hello,

Thanks for reporting this, I'll push a fix.

**Comment by volcacius** [comment]
It's fixed in the dev branch, feel free to reopen the issue if you have any more problems.

**Comment by MaenMallah** [comment]
Hello volcacius ,

Thanks, your fix solves the first issue but now I got another issue when trying to access attributes from a higher level: for example: 

```python
class Container(ExtendedInjector):
    adder = ADD_Complex
    x = this.X.complex
    y = this.Y.complex

    y_im = 10
    class X(ExtendedInjector):
        complex = Complex
        re = 5
        im = (this <<1).y_im
    class Y(ExtendedInjector):
        complex = Complex
        re = -1
        im = 0
````

throws an error: "You tried to shift this more times than Injector has levels"

However, I can solve the error by making class X and Y inherit from Injector instead of ExtendedInjector. Not sure if this would create other problems later but it seems to work.

**Comment by volcacius** [comment]
Thanks, I'll have a look. In general you need an ExtendedInjector only if you need to return a this.something or a class to inject from a @value function (example https://github.com/Xilinx/brevitas/blob/a5bfd6dc5e030f0047ac1ee47932b60e8e873e17/src/brevitas/quant/solver/common.py#L121), which is something the various WeightQuantSolver/ActQuantSolver do. If you don't need the functionality at a certain level of nesting it's fine to just use an Injector.

**Comment by MaenMallah** [comment]
Hello Valcacis, 

Thanks for the all support and clarification. In my case I am returning a Pytorch autograd Function's apply method. My nested class to post process the weights after quantization for example is as follows:

```python
class Post(Injector):
        variation = Var
        quant_var = (this <<1).post_quant_var
        post_quant_impl_type = (this <<1).post_quant_impl_type
        @value
        def variation_impl(post_quant_impl_type):
            if post_quant_impl_type == PrePostQuantType.VAR_ABS:
                return AddNoise_impl
            if post_quant_impl_type == PrePostQuantType.VAR_REL:
                return MulNoise_impl
```
where:
```python
class AddNoise(torch.autograd.Function):
    ...

AddNoise_impl = AddNoise.apply
```

So I am using the @value function to return a method not a class. That should be alright and not cause problems later, right? Now everything works functionally as I intend. 

Regards,
Maen

**Comment by MaenMallah** [comment]
Hello @volcacius , do you know when this change/fix will make to the master and stable version?

**Comment by volcacius** [comment]
Hi @MaenMallah ,
I have been busy with a lot of other stuff lately but I'm trying to get back on track in the next couple of weeks and go out with a release.
