### ISSUE TITLE
Fail to load pre-trained weight in MobileNet

### ISSUE THREAD

**Issue by laochonlam** [Xilinx/brevitas#386]
Hello Brevitas developers, 

It fails when I load the MobileNet model from brevitas_examples with `pretrained=True`, but it works perfectly when I change the `pretrained` flag to `False`.

```python
from brevitas_examples.imagenet_classification import quant_mobilenet_v1_4b
mobilenet = quant_mobilenet_v1_4b(pretrained=True)
```

The error message is attached below:
```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    mobilenet = quant_mobilenet_v1_4b(pretrained=True)
  File "/home/laochanlam/anaconda3/envs/pynq_dev/lib/python3.7/site-packages/brevitas_examples/imagenet_classification/models/__init__.py", line 32, in quant_mobilenet_v1_4b
    model, _ = model_with_cfg('quant_mobilenet_v1_4b', pretrained)
  File "/home/laochanlam/anaconda3/envs/pynq_dev/lib/python3.7/site-packages/brevitas_examples/imagenet_classification/models/__init__.py", line 27, in model_with_cfg
    model.load_state_dict(state_dict, strict=True)
  File "/home/laochanlam/anaconda3/envs/pynq_dev/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MobileNet:
        size mismatch for features.init_block.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
        size mismatch for features.stage1.unit1.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
        size mismatch for features.stage2.unit1.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
        size mismatch for features.stage2.unit2.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
        size mismatch for features.stage3.unit1.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
        size mismatch for features.stage3.unit2.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
        size mismatch for features.stage4.unit1.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
        size mismatch for features.stage4.unit2.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
        size mismatch for features.stage4.unit3.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
        size mismatch for features.stage4.unit4.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
        size mismatch for features.stage4.unit5.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
        size mismatch for features.stage4.unit6.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
```
---

Then I tried the [test script](https://github.com/Xilinx/brevitas/blob/master/tests/brevitas_finn/brevitas_examples/test_mobilenet_finn_export.py) with FINN's environment, it also fails. I got the same error message:
```
======================================================= test session starts ========================================================
platform linux -- Python 3.7.4, pytest-5.3.4, py-1.8.1, pluggy-0.13.1
rootdir: /home/laochanlam/git/brevitas, inifile: pytest.ini
plugins: typeguard-2.12.1, astropy-header-0.1.1, arraydiff-0.3, openfiles-0.4.0, remotedata-0.3.2, doctestplus-0.5.0, hypothesis-4.54.2
collected 1 item                                                                                                                   

test_mobilenet_finn_export.py::test_mobilenet_v1_4b[True] FAILED                                                             [100%]

============================================================= FAILURES =============================================================
____________________________________________________ test_mobilenet_v1_4b[True] ____________________________________________________

pretrained = True

    @ort_mac_fail
    @pytest.mark.parametrize("pretrained", [True])
    def test_mobilenet_v1_4b(pretrained):
        finn_onnx = "mobilenet_v1_4b.onnx"
>       mobilenet = quant_mobilenet_v1_4b(pretrained)

test_mobilenet_finn_export.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../../../anaconda3/envs/pynq_dev/lib/python3.7/site-packages/brevitas_examples/imagenet_classification/models/__init__.py:32: in quant_mobilenet_v1_4b
    model, _ = model_with_cfg('quant_mobilenet_v1_4b', pretrained)
../../../../../anaconda3/envs/pynq_dev/lib/python3.7/site-packages/brevitas_examples/imagenet_classification/models/__init__.py:27: in model_with_cfg
    model.load_state_dict(state_dict, strict=True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = MobileNet(
  (features): Sequential(
    (init_block): ConvBlock(
      (conv): QuantConv2d(
        3, 32, kernel_siz... )
        )
        (msb_clamp_bit_width_impl): Identity()
        (zero_point): StatelessBuffer()
      )
    )
  )
)
state_dict = OrderedDict([('features.init_block.conv.weight', tensor([[[[ 5.7093e-40,  1.2611e-40,  5.4048e-40],
          [ 6.2409...ge5.unit2.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value', tensor(3.2725))])
strict = True

    def load_state_dict(self, state_dict: 'OrderedDict[str, Tensor]',
                        strict: bool = True):
        r"""Copies parameters and buffers from :attr:`state_dict` into
        this module and its descendants. If :attr:`strict` is ``True``, then
        the keys of :attr:`state_dict` must exactly match the keys returned
        by this module's :meth:`~torch.nn.Module.state_dict` function.
    
        Args:
            state_dict (dict): a dict containing parameters and
                persistent buffers.
            strict (bool, optional): whether to strictly enforce that the keys
                in :attr:`state_dict` match the keys returned by this module's
                :meth:`~torch.nn.Module.state_dict` function. Default: ``True``
    
        Returns:
            ``NamedTuple`` with ``missing_keys`` and ``unexpected_keys`` fields:
                * **missing_keys** is a list of str containing the missing keys
                * **unexpected_keys** is a list of str containing the unexpected keys
    
        Note:
            If a parameter or buffer is registered as ``None`` and its corresponding key
            exists in :attr:`state_dict`, :meth:`load_state_dict` will raise a
            ``RuntimeError``.
        """
        missing_keys: List[str] = []
        unexpected_keys: List[str] = []
        error_msgs: List[str] = []
    
        # copy state_dict so _load_from_state_dict can modify it
        metadata = getattr(state_dict, '_metadata', None)
        state_dict = state_dict.copy()
        if metadata is not None:
            # mypy isn't aware that "_metadata" exists in state_dict
            state_dict._metadata = metadata  # type: ignore[attr-defined]
    
        def load(module, prefix=''):
            local_metadata = {} if metadata is None else metadata.get(prefix[:-1], {})
            module._load_from_state_dict(
                state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
            for name, child in module._modules.items():
                if child is not None:
                    load(child, prefix + name + '.')
    
        load(self)
        del load
    
        if strict:
            if len(unexpected_keys) > 0:
                error_msgs.insert(
                    0, 'Unexpected key(s) in state_dict: {}. '.format(
                        ', '.join('"{}"'.format(k) for k in unexpected_keys)))
            if len(missing_keys) > 0:
                error_msgs.insert(
                    0, 'Missing key(s) in state_dict: {}. '.format(
                        ', '.join('"{}"'.format(k) for k in missing_keys)))
    
        if len(error_msgs) > 0:
            raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
>                              self.__class__.__name__, "\n\t".join(error_msgs)))
E           RuntimeError: Error(s) in loading state_dict for MobileNet:
E               size mismatch for features.init_block.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
E               size mismatch for features.stage1.unit1.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
E               size mismatch for features.stage2.unit1.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
E               size mismatch for features.stage2.unit2.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
E               size mismatch for features.stage3.unit1.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
E               size mismatch for features.stage3.unit2.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
E               size mismatch for features.stage4.unit1.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
E               size mismatch for features.stage4.unit2.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
E               size mismatch for features.stage4.unit3.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
E               size mismatch for features.stage4.unit4.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
E               size mismatch for features.stage4.unit5.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).
E               size mismatch for features.stage4.unit6.pw_conv.activation.act_quant.fused_activation_quant_proxy.tensor_quant.scaling_impl.value: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([]).

../../../../../anaconda3/envs/pynq_dev/lib/python3.7/site-packages/torch/nn/modules/module.py:1483: RuntimeError
======================================================== 1 failed in 1.80s =========================================================
```
Is it because the structure of pre-trained weight of MobileNet is outdated or something? it would be appreciated if there is a solution to make it works, thanks!

Best,
Lam

**Comment by volcacius** [comment]
Hi Lam,

Sorry I had a regression in the current release with per channel activation quantization. It's fixed in the dev branch.
