### ISSUE TITLE
Exporting with FINNManager fails

### ISSUE THREAD

**Issue by jacopoabramo** [Xilinx/brevitas#392]
Greetings,

I've been working on an Iris classification model to train myself on how to use Brevitas and the FINN framework in order to deploy such model on a PYNQ board. This is an excerpt of my code:

```python
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from torch import nn
from torch.nn import Module, functional as F
from brevitas.quant import Int8ActPerTensorFloat as InQuant, Int8Bias as BiasQuant
from brevitas.export import FINNManager
import torch
import brevitas.nn as qnn
import numpy as np

class QuantizedIrisModel(Module):
    def __init__(self):
        super(QuantizedIrisModel, self).__init__()
        self.inLayer = qnn.QuantLinear(in_features=4, out_features=8, input_quant=InQuant, bias=True, bias_quant=BiasQuant, weight_bit_width=4, return_quant_tensor=True)
        self.inReLU = qnn.QuantReLU(bit_width=4, return_quant_tensor=True)
        self.midLayer = qnn.QuantLinear(in_features=8, out_features=24, bias=True, bias_quant=BiasQuant, weight_bit_width=4, return_quant_tensor=True)
        self.midReLU = qnn.QuantReLU(bit_width=4, return_quant_tensor=True)
        self.outLayer = qnn.QuantLinear(in_features=24, out_features=3, bias=False, bias_quant=BiasQuant, weight_bit_width=4, output_quant=InQuant)

    def forward(self, x):
        out = self.inReLU(self.inLayer(x))
        out = self.midReLU(self.midLayer(out))
        out = self.outLayer(out)
        return out

def train(model, train_in, train_out, is_quantized = True):
    loss_fn = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    epochs = 250
    if is_quantized:
        X = torch.from_numpy(train_in*10).type(torch.long)
        y = torch.from_numpy(train_out).type(torch.long)
    else:
        X = torch.from_numpy(train_in).type(torch.float)
        y = torch.from_numpy(train_out).type(torch.long)
    for epc in range(epochs):
        pred = model(X)
        loss = loss_fn(pred, y)
        # back propagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(f"[Epoch {epc + 1}] - Loss: {loss.item():10.8f}")

def test(model, test_in, test_out, is_quantized = True):
    model.eval()
    correct = 0
    with torch.no_grad():
        if is_quantized:
            X = torch.from_numpy(test_in*10).type(torch.long)
            y = torch.from_numpy(test_out).type(torch.long)
        else:
            X = torch.from_numpy(test_in).type(torch.float)
            y = torch.from_numpy(test_out).type(torch.long)
        pred = model(X)
        correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    correct /= len(test_out)
    print(f"Testing: accuracy {(100*correct):>0.1f}")

device = "cuda" if torch.cuda.is_available() else "cpu"
iris_model = QuantizedIrisModel().to(device)
data = load_iris()
is_quantized = True

train_in, test_in, train_out, test_out = train_test_split(data["data"], data["target"], test_size=0.20)
train(iris_model, train_in, train_out, is_quantized)
test(iris_model, test_in, test_out, is_quantized)
FINNManager.export(iris_model, input_shape=(1, 4), export_path="models/iris_onnx.onnx")
```

I tried to replicate the original model I had using Brevitas, and I wanted to export it as an ONNX model in order to work with FINN dataflow to create an IP.

The training works but when trying to export it I get the following traceback:

```
Traceback (most recent call last):
  File "IrisBrevitas.py", line 101, in <module>
    FINNManager.export(iris_model, input_shape=(1, 4), export_path="models/iris_onnx.onnx")
  File "/home/jacopo/.local/lib/python3.8/site-packages/brevitas/export/onnx/finn/manager.py", line 125, in export
    onnx_model = cls.export_onnx(
  File "/home/jacopo/.local/lib/python3.8/site-packages/brevitas/export/onnx/manager.py", line 99, in export_onnx
    module.apply(lambda m: cls.set_export_mode(m, enabled=True))
  File "/home/jacopo/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 659, in apply
    module.apply(fn)
  File "/home/jacopo/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 660, in apply
    fn(self)
  File "/home/jacopo/.local/lib/python3.8/site-packages/brevitas/export/onnx/manager.py", line 99, in <lambda>
    module.apply(lambda m: cls.set_export_mode(m, enabled=True))
  File "/home/jacopo/.local/lib/python3.8/site-packages/brevitas/export/onnx/finn/manager.py", line 104, in set_export_mode
    _set_layer_export_mode(module, enabled)
  File "/home/jacopo/.local/lib/python3.8/site-packages/brevitas/export/manager.py", line 100, in _set_layer_export_mode
    m.export_mode = enabled
  File "/home/jacopo/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1225, in __setattr__
    object.__setattr__(self, name, value)
  File "/home/jacopo/.local/lib/python3.8/site-packages/brevitas/nn/mixin/base.py", line 167, in export_mode
    self.export_handler.prepare_for_export(self)
  File "/home/jacopo/.local/lib/python3.8/site-packages/brevitas/export/onnx/finn/handler/parameter.py", line 83, in prepare_for_export
    self.validate(module)
  File "/home/jacopo/.local/lib/python3.8/site-packages/brevitas/export/onnx/finn/handler/parameter.py", line 23, in validate
    assert not module.is_input_quant_enabled
AssertionError
```

I don't know exactly what's missing within the model to create such error, or if I'm even using the correct export function (I checked the example notebooks and it seems that there are different export functions to be used). Does anybody have some inputs on where's the error? Secondly: is the input shape correct? My model should take as input 4 8-bit features.

I apologize if this is a duplicate question and thank you in advance.

**Comment by possoj** [comment]
Hi, the assertion expects the input quantization to be disabled. So I guess instead of quantizing the input layer with input_quant=InQuant, you should use qnn.QuantIdentity before the first layer. Lok at the LowPrecisionLeNet example in the gitHub readme :)

The input shape looks good if you have batch size of 1.

**Comment by jacopoabramo** [comment]
Hi @possoj , thank you for your reply. After your suggestion I added a QuantIdentity layer and now it seems to correctly write the model. However I got the following warnings:

```
WARNING: The shape inference of finn.custom_op.general::MultiThreshold type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MatMul type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of {DOMAIN_STRING}::Add type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MultiThreshold type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MatMul type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of {DOMAIN_STRING}::Add type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MultiThreshold type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MatMul type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MultiThreshold type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MatMul type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of {DOMAIN_STRING}::Add type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MultiThreshold type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MatMul type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of {DOMAIN_STRING}::Add type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MultiThreshold type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MatMul type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MultiThreshold type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MatMul type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of {DOMAIN_STRING}::Add type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MultiThreshold type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MatMul type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of {DOMAIN_STRING}::Add type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MultiThreshold type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of finn.custom_op.general::MatMul type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
```

Are they somewhat relevant?

Moreover this is the output graph shown in Netron:

![iris_onnx onnx](https://user-images.githubusercontent.com/20145526/159036593-3a26d1fa-8980-4acf-9504-4c63db5fbc24.png)

I don't exactly understand the reason why the output is noted as 46.

**Comment by possoj** [comment]
Hi @jacopoabramo, I meet the same warnings when I export my models. I have not tried yet to go beyond the export with FINNManager. 

To control the name of your inputs and outputs you may add arguments to the FINN export function. FINNManager will call torch.onnx.export. So you can use the same arguments (see https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html).

Here is how I call the export function:

```
from brevitas.export import export_finn_onnx 
out_model = export_finn_onnx(input_model, input_shape=tuple(image_ex.shape), export_path="Model.onnx",
                     export_params=True, do_constant_folding=True,
                     input_names=['input'], output_names=['output'])
```

**Comment by jacopoabramo** [comment]
Hi @possoj , thank you, that did the trick.
